### ISSUE TITLE
End game type not updated to check mate

### ISSUE THREAD

**Issue by druzil** [rudzen/ChessLib#24]
{8/8/8/3Q4/4R1k1/8/7K/6N1 b - - 4 5}

I would have expected IGame.GameEndType == EGameEndType.CheckMate

**Comment by rudzen** [comment]
The library does not currently flag it as EGameEndType.CheckMate. The reason for this is that the original code which flagged it, is located outside the library. I had planned to move the checkmate check into the library. But since it just involves checking the move count, it would require an additional move generation to do that. Until I've improved the move generator to be able to just generate moves for evasions, I would recommend you just check on generated move count and set the flag yourself. However it is able to flag the various draw states in Game.UpdateDrawTypes().
