### ISSUE TITLE
Square.None

### ISSUE THREAD

**Issue by JMSSVLC** [rudzen/ChessLib#57]
I have just seen that some of the properties of Square.None are wrong and other ones fire an exception. In particular, File property is "b" and Rank is "9". Maybe File.None and Rank.None should be defined. I am not sure about the penalties in code speed, and if this issue is "on purpose"

**Comment by rudzen** [comment]
It is intended the way it currently is.
_Square.None_ is a special case since it reflects that the square is not a set square, since the value 0 is _Square.A1_.
The recommended use it to check if a square is None before using it.
Fx it is used in regard to EnPassant square in State.

Rank.None and File.None is not really needed since a square with the value Square.None is already an indication that the square is not set.
